### ISSUE TITLE
output m3u not show

### ISSUE THREAD

**Issue by heryartshtv** [SxtBox/OVOO_APIS#1]
hi admin, I'm trying to use it on my ovoo for vlc php, when I try to get_all_tv_channel_by_category the output doesn't work perfectly, the m3u result doesn't appear like the name, link stream, tvg logo and others, only the category name appears.

and if i use get_features_genre_and_movie, m3u output result not showing all for information.

I'm using ovoo version 3.2.9, is there anything that needs to be fixed?

**Comment by SxtBox** [comment]
check again repo /V_3.28.xx/

**Comment by SxtBox** [comment]
check again repo /V_3.28.xx/
